[theme]
file = "/home/nizos/.config/i3status-rust/themes/ayu_mirage.toml"
[icons]
name = "awesome5"
[icons.overrides]
time = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
format = "{output_name} {volume}"
on_click = "bash ~/.scripts/audio_output_switch"
[block.mappings]
"alsa_output.usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00.analog-stereo" = "Headphones"
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "Stereo"

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "keyboard_layout"
driver = "localebus"
format = "\uf11c {layout}"

[[block]]
block = "time"
interval = 1
format = "\uf073 %A %d %m %Y   \uf017 %R"


