#!/bin/bash

# Name: keyboard_layout_switch

function get_current_layout() {
	xkb_current=$(setxkbmap -query | grep layout | sed -n -e 's/^.*layout:     //p')
	echo "$xkb_current"
}

function set_current_layout() {
	new_layout=$1
	xkb_set=$(setxkbmap $new_layout)
        $xkb_set
}

function set_next_layout() {
	current_layout=$(get_current_layout)

	if [[ "$current_layout" == "us" ]]; then
		set_current_layout "se"
	elif [[ "$current_layout" == "se" ]]; then
		set_current_layout "ara"
	else
		set_current_layout "us"
	fi
}

set_next_layout
