idle_bg = "#242936"
idle_fg = "#CCCAC2"
info_bg = "#80BFFF"
info_fg = "#1F2430"
good_bg = "#87D96C"
good_fg = "#1F2430"
warning_bg = "#F29E74"
warning_fg = "#1F2430"
critical_bg = "#F27983"
critical_fg = "#1F2430"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
